boostsec/registry_validator/validate_rules_db.py, tests/unit/scanner/test_validate_rules_db.py
Current behavior:
- There is no information about the file that is being scanned. 
```
Validating rules...
Rules are valid!
Validating rules...
Rules are valid!
Validating rules...
ERROR: Rules db is invalid: \"'categories' is a required property\"
```
Expected behavior:
- The scanner informs what file is being scanned.
```
Validating boostsecurityio/brakeman-scanner/rules.yaml
Validating boostsecurityio/snyk-scanner/rules.yaml
Validating boostsecurityio/semgrep-scanner/rules.yaml
ERROR: Rules db is invalid: \"'categories' is a required property\"
```
=> Implemented log to show current scanning file

action.yaml, boostsec/registry_validator/upload_rules_db.py, tests/unit/scanner/test_upload_rules_db.py
There is a bug in the action when the file is moved with a commit. When it happens the second column on git diff is the old path and the third is the new path, example:
```
R089    old/path/module.yaml   new/path/module.yaml
R100    old/path/rules.yaml    new/path/rules.yaml
M       my/scanner/module.yaml
```
Since the action only used the second column the old path was passed to the script.
current behavior
```
old/path/module.yaml
my/scanner/module2.yaml
old/path/rules.yaml
my/scanner/module.yaml
```
This PR will take into consideration both the second and third column
```
old/path/module.yaml
new/path/module.yaml
my/scanner/module2.yaml
old/path/rules.yaml
new/path/rules.yaml
my/scanner/module.yaml
```
=> Print all second and third column from git diff

action.yaml, boostsec/registry_validator/upload_rules_db.py, tests/unit/scanner/conftest.py, tests/unit/scanner/test_upload_rules_db.py, tests/unit/scanner/test_validate_rules_db.py
Rules can now be imported from other namespace. Imports are reference by the namespace name (ex: boost/module). If conflicting rule names are found, they get overwritten by the order defined in the file, giving the ability to update an imported rule.
Other changes:
- Moved the `registry_path` fixture to conftest
- Updated helper function to create module to include a namespace (useful for creating import tests)
- Added a new cli input reference the registry path (identical to the validator). This is needed since import are only specified by a namespace, without it, we would have to guess the root folder of imported rules. It also simplifies testing.
=> BST-3554: Merge & upload imported rules

.circleci/config.yml, action.yaml, pyproject.toml
`poetry-core` recently had an update which is not compatible with the current poetry version (`1.2.0b1`). I think the issue was also caused by the `build-system` entry in `pyproject.toml` which would always get the latest version of `poetry-core`.
=> fix: updated poetry to v1.4.2

boostsec/registry_validator/upload_rules_db.py, tests/unit/scanner/test_upload_rules_db.py
I'm blocked from shipping this https://github.com/boostsecurityio/scanner-testing/actions/runs/5060855775/jobs/9084282167#step:3:299
This is a bugfix to support the legacy `default` namespace, which has a hardcoded mapping to the native-scanner module.
=> BST-5645 - Bugfix to support legacy default namespace

boostsec/registry_validator/upload_rules_db.py, tests/unit/scanner/test_upload_rules_db.py
Now that the API accept a default_rule, we don't need to manually create a default entry in the input rules. We now simply add it as a normal rule but pass an extra variable `defaultRule` to the GQL mutation
depends-on: https://github.com/boostsecurityio/boostsec-rules-management/pull/52
=> BST-5725: Removed default_rule overwrite & send it in GQL mutation

README.md, action.yaml, boostsec/registry_validator/shared.py, boostsec/registry_validator/upload_rules_db.py, boostsec/registry_validator/validate_rules_db.py, tests/unit/scanner/conftest.py, tests/unit/scanner/test_upload_rules_db.py, tests/unit/scanner/test_validate_rules_db.py
Rules realm are similar to scanners, but they do not require to be defined as part of a scanner module. They are also defined by namespace, so the validate & upload steps now needs a reference to the scanners and realm location.
Next, I will add some validation to enforce the uniqueness between scanners & rules-realm.
=> BST-5832: Import from rules realm

action.yaml, boostsec/registry_validator/validate_namespaces.py, tests/unit/scanner/test_validate_namespaces.py
Added validation to enforce that a namespace is unique between the rules realm & the scanner modules. The path relative to the rules realm base folder is used as a namespace.
=> BST-5833: Validate unique namespace between rules realm & modules

boostsec/registry_validator/upload_rules_db.py, tests/unit/scanner/test_upload_rules_db.py
Like regular rules, default rule can be imported, and the latest imported one should take precedence over the others. In the previous version, any import default would just get ignored.
=> BST-5922: Fix imported default ignored

boostsec/registry_validator/shared.py, boostsec/registry_validator/testing/factories.py, boostsec/registry_validator/upload_rules_db.py, boostsec/registry_validator/validate_rules_db.py, tests/unit/scanner/test_upload_rules_db.py, tests/unit/scanner/test_validate_rules_db.py, tests/unit/test_shared.py
All the validations rules (except for the imports) were moved in the rules and rules db models. The corresponding validations tests were moved in the shared test file.
This changes also has the added bonus of logging the exact rule & field containing the error, rather than just logging that the whole file has an issue. (ex: `rules.my-rule-1.ref is missing`)
Since pydantic it now used to validate the models structure, the json schema was also removed.
=> BST-5993: Moved rules validations inside rules models

action.yaml, boostsec/registry_validator/parameters.py, boostsec/registry_validator/shared.py, boostsec/registry_validator/upload_rules_db.py, boostsec/registry_validator/validate_namespaces.py, boostsec/registry_validator/validate_rules_db.py, tests/unit/scanner/test_upload_rules_db.py, tests/unit/scanner/test_validate_namespaces.py, tests/unit/scanner/test_validate_rules_db.py, tests/unit/test_shared.py
The CLI options to specify the module, scanners or rules-realm paths were replaced by a single option: registry-path. Now, the path of the scanners and rules-realm are derived from the provided base registry.
This was made in prevision of an upcoming change to the way updated modules/rules are tracked.
=> BST-5993: Registry base path option

boostsec/registry_validator/config.py, boostsec/registry_validator/models.py, boostsec/registry_validator/schema.py, boostsec/registry_validator/testing/factories.py, boostsec/registry_validator/upload_rules_db.py, boostsec/registry_validator/validate_namespaces.py, boostsec/registry_validator/validate_rules_db.py, tests/conftest.py, tests/integration/conftest.py, tests/integration/samples/rules-realm/boostsecurityio/mitre-cwe/rules.yaml, tests/integration/samples/scanners/boostsecurityio/simple-scanner/module.yaml, tests/integration/samples/scanners/boostsecurityio/simple-scanner/rules.yaml, tests/integration/samples/scanners/others/missing-rules/module.yaml, tests/integration/samples/scanners/others/only-import/module.yaml, tests/integration/samples/scanners/others/only-import/rules.yaml, tests/integration/samples/scanners/others/overload/module.yaml, tests/integration/samples/scanners/others/overload/rules.yaml, tests/integration/samples/scanners/others/with-placeholder/module.yaml, tests/integration/samples/scanners/others/with-placeholder/rules.yaml, tests/integration/test_upload_rules_db.py, tests/unit/scanner/conftest.py, tests/unit/scanner/test_upload_rules_db.py, tests/unit/scanner/test_validate_rules_db.py, tests/unit/test_config.py, tests/unit/test_schema.py
The import & updated logic was modified to handle detection of module whose dependencies were modified. The new logic is to first load all the scanners & rules-realm from the registry, marking the updated namespace, and finally resolving the rules, default rule and updated status for each scanner module.
To avoid confusion, the shared module was split into schema, config & models.
Integrations tests were also added in order to better e2e test the upload. Those tests create a temporary git repo for the registry, copies the module & rules yaml files and run cli. This setup is closer to the real use of the cli. They are not considered "module tests" since the request to the backend are still mocked.
=> BST-5993: Detect updated dependencies

tests/integration/conftest.py, tests/integration/samples/rules-realm/invalids/empty-rules/module.yaml, tests/integration/samples/rules-realm/invalids/missing-category/rules.yaml, tests/integration/samples/rules-realm/invalids/multi-defaults/rules.yaml, tests/integration/samples/scanners/invalids/empty-rules/module.yaml, tests/integration/test_upload_rules_db.py, tests/integration/test_validate_rules_db.py, tests/unit/scanner/test_validate_rules_db.py
Moved all tests that use the validate cli app directly to the integration tests file. The tests were also reworked to use the same pattern as for the upload: copy sample yaml files to a temporary git repo and run the cli on them.
The `use_sample` utility function to setup these files was converted to a fixture to help with reusability.
=> BST-6070: Validate rules db integration tests

tests/integration/samples/scanners/invalids/duplicate-a/module.yaml, tests/integration/samples/scanners/invalids/duplicate-b/module.yaml, tests/integration/samples/scanners/invalids/missing-namespace/module.yaml, tests/integration/samples/server-side-scanners/boostsecurityio/simple-scanner/module.yaml, tests/integration/samples/server-side-scanners/boostsecurityio/simple-scanner/rules.yaml, tests/integration/test_validate_namespace.py, tests/unit/scanner/test_validate_namespaces.py
Moved all tests that use the validate namespace cli directly to the integration tests module. The tests were also slightly modified to use the same pattern as the other integration tests.
Tests for namespace uniqueness between scanners & rules-realm were merged into a single parameterized test.
=> BST-6070: Validate namespace integration tests

boostsec/registry_validator/errors.py, boostsec/registry_validator/schema.py, boostsec/registry_validator/testing/factories.py, boostsec/registry_validator/validate_namespaces.py, boostsec/registry_validator/validate_rules_db.py, poetry.lock, pyproject.toml, tests/integration/test_validate_namespace.py, tests/unit/scanner/test_validate_namespaces.py, tests/unit/test_errors.py
Like what was done for the rules and rules db, the schema & validation was converted to a pydantic model. Package `jsonschema` was also removed since it is no longer used.
New module `errors` was created to share conversion of pydantic validation errors. I plan to improve the overall errors handling in a future pr.
=> BST-6070: Validate namespace module schema

boostsec/registry_validator/config.py, boostsec/registry_validator/schema.py, boostsec/registry_validator/testing/factories.py, boostsec/registry_validator/validate_namespaces.py, tests/integration/samples/server-side-scanners/boostsecurityio/simple-scanner/module.yaml, tests/integration/samples/server-side-scanners/invalids/duplicate-a/module.yaml, tests/integration/samples/server-side-scanners/invalids/duplicate-b/module.yaml, tests/integration/samples/server-side-scanners/invalids/missing-namespace/module.yaml, tests/integration/test_validate_namespace.py, tests/unit/scanner/conftest.py, tests/unit/scanner/test_validate_namespaces.py, tests/unit/test_config.py, tests/unit/test_schema.py
Added validation for the new server-side scanners. These scanners are almost identical to the regular scanner, but they don't have steps, must have `server_side: true`. Additional validation to the module schema was added to make sure that a module without rules must be set as server-side. Also, check that namespaces are unique across all scanners, server-side or not.
=> BST-6070: Validate server-side scanners

boostsec/registry_validator/upload_rules_db.py, tests/integration/test_upload_rules_db.py, tests/unit/scanner/test_upload_rules_db.py
Detect changes & upload server-side the same way regular scanners are. Since there is no difference in how the server-side or regular scanners rules are handled, we only have to monitor an extra directory and process/upload the changed rules.
=> BST-6077: Upload server-side scanners

boostsec/registry_validator/errors.py, boostsec/registry_validator/schema.py, boostsec/registry_validator/testing/factories.py, tests/integration/samples/scanners/boostsecurityio/simple-scanner/module.yaml, tests/integration/samples/scanners/invalids/duplicate-a/module.yaml, tests/integration/samples/scanners/invalids/duplicate-b/module.yaml, tests/integration/samples/scanners/invalids/empty-rules/module.yaml, tests/integration/samples/scanners/invalids/missing-namespace/module.yaml, tests/integration/samples/server-side-scanners/boostsecurityio/simple-scanner/module.yaml, tests/integration/samples/server-side-scanners/invalids/duplicate-a/module.yaml, tests/integration/samples/server-side-scanners/invalids/duplicate-b/module.yaml, tests/integration/samples/server-side-scanners/invalids/empty-rules/module.yaml, tests/integration/samples/server-side-scanners/invalids/missing-namespace/module.yaml, tests/unit/scanner/test_validate_namespaces.py, tests/unit/test_errors.py, tests/unit/test_schema.py
Scanners now needs to defined a scan types which needs to be one of the predefined possible values. A scanner can have multiple, but at least one is required.
=> BST-6121: Validate scan types

boostsec/registry_validator/schema.py, tests/integration/samples/server-side-scanners/boostsecurityio/simple-scanner/module.yaml, tests/integration/samples/server-side-scanners/invalids/duplicate-a/module.yaml, tests/integration/samples/server-side-scanners/invalids/duplicate-b/module.yaml, tests/integration/samples/server-side-scanners/invalids/empty-rules/module.yaml, tests/integration/samples/server-side-scanners/invalids/missing-namespace/module.yaml
Server-side scanners scan-types are defined in the backend, having them defined in the module file is not needed.
=> BST-6424: Remove scan-types for server-side scanners

boostsec/registry_validator/schema.py
New scan-type 'license' for scanners that emits findings based on licenses found.
drive-by: sorted scan-type enums
=> BST-9548: add license scan-type

boostsec/registry_validator/upload_rules_db.py, boostsec/registry_validator/validate_rules_db.py, tests/integration/samples/server-side-scanners/boostsecurityio/simple-server-scanner/module.yaml, tests/integration/samples/server-side-scanners/boostsecurityio/simple-server-scanner/rules.yaml, tests/integration/samples/server-side-scanners/others/only-import/rules.yaml, tests/integration/samples/server-side-scanners/others/only-server-import/module.yaml, tests/integration/samples/server-side-scanners/others/only-server-import/rules.yaml, tests/integration/test_upload_rules_db.py, tests/integration/test_validate_rules_db.py, tests/unit/scanner/test_upload_rules_db.py, tests/unit/scanner/test_validate_rules_db.py
The server-side scanner were ignored in the import logic, so trying to import rules from another server-side scanner was always rejected in the validation step.
=> BST-11165: allow imports from server-side scanner rules
